#!/bin/bash 
  
cd
rm -rf AUTORUN-CCMINER-X
git clone https://github.com/pichetx/AUTORUN-CCMINER-X 
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-X/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-ip edit-miner run-miner
cd
cd AUTORUN-CCMINER-X 
chmod +x setupdate.sh
sh setupdate.sh